[project]
name = "aether"
description = "aether"
requires-python = ">=3.9"

[tool.black]
line-length = 1024
include = '\.pyi?$'

[tool.flake8]
max-line-length = 1024
exclude = [
    ".venv",
    "build"
]
ignore = [
    "E203",
    "W503",
    "E402",
    "E501",
]

[tool.isort]
profile = "black"
